### ISSUE TITLE
Questions about MIP Tracking Variables

### ISSUE THREAD

**Issue by aechavez** [juan-mlr/ecal-bdt#10]
There are a few things that I noticed about the MIP tracking variables that I thought might be worth addressing. Feel free to split this up into multiple issues if need be.

- Why are epSep and epAng commented out for now? Is there something odd about their distributions that you haven't resolved yet?

- In lines 451-452 of the treeMaker, it looks like photonTerritoryHits defaults to the value of nReadoutHits in certain cases. Is this correct?

- In lines 453-454 of the treeMaker, it looks like TerritoryRatio defaults to a value of 10 in certain cases. And this happens twice in a row. Is that correct? Neither of those things makes sense to me.

**Comment by juan-mlr** [comment]
- Both labeled as unused due to pt bias concers in Phillip's version of the EcalVeto. epSep is the exact the same as it was in v9. Also epDot and epAng aren't the same. epDot is the dot product of the normalized trajectories and it what was I put in the v9 bdts. In the analyzer, it was changed to epAng which was was actually an angle because it used acos(epDot). I still think they're okay given the flatmess of the bias plots, but I think it came up again when i wasn't around to defend it and others decided they should still be taken out.

- There is an impereft subilty in that which is: "what if the photon isn't present either?", but it also is fine I think. It's just saying if the electron isn't there, then all the hits are the photon's

- Above also explains the 10s because it'd be some finite value over 0 so i just went with something relatively big.

**Comment by aechavez** [comment]
All those points seem sensible. I still think line 454 is a mistake though, and that should probably be fixed. (Line 453 and line 454 are identical)

**Comment by aechavez** [comment]
All those points seem sensible, and I just saw that you changed the TerritoryRatio -> fullTerritoryRatio. So this issue can probably be closed now
