### ISSUE TITLE
Feature Clarifications

### ISSUE THREAD

**Issue by juan-mlr** [juan-mlr/ecal-bdt#6]
Add straight track merging (present in python code i originally put into the bdt, but it's not in the analyzer) if straightTrack distribution(s) are not as expected
Also, need clarification on what exact feats (linregTrack(s), territory stuff) should be added. 
@aechavez A master list would be good, it can be made a task list in a subsequent comment.

**Comment by aechavez** [comment]
List of all the mip tracking features from the v9 bdts:

- [x]  nearPhotonHits
- [x]  firstPhotonLayer
- [x]  electronTerritoryHits
- [x]  photonTerritoryHits
- [x]  TerritoryRatio
- [x]  fullElectronTerritoryHits
- [x]  fullPhotonTerritoryHits
- [x]  fullTerritoryRatio
- [x]  trajsep
- [x]  trajdot
- [x]  straight4

I would say put these mip tracking features in for now

**Comment by juan-mlr** [comment]
Which ones are actually used though? I want to prioritize those.

**Comment by aechavez** [comment]
seg-mipv4 uses all of them. seg-mipv3 just uses:
- [x] nearPhotonHits
- [x] firstPhotonLayer
- [x] photonTerritoryHits
- [x] trajsep
- [x] trajdot
- [x] straight4

So I would say to prioritize these variables over the others since these are invariably the ones that are used in the BDT with a feature list equal to the intersection of seg-mipv3's and seg-mipv4's feature lists
